// src/lib/mockData.ts

export type MockDish = {
  id: number;
  name: string;
  restaurant_name: string;
  category: string;
  description: string;
  image_url: string;
  price?: string;
  averageRating: number;
  reviewCount: number;
  spice_level: number;
  sweetness_level: number;
  tag?: string;
};

export const MOCK_DISHES: MockDish[] = [
  {
    id: 101,
    name: "Hyderabadi Dum Biryani",
    restaurant_name: "Paradise Spice House",
    category: "Biryani",
    description: "Fragrant basmati rice layered with aromatic spices, caramelized onions, and tender marinated pieces.",
    image_url: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&auto=format&fit=crop&q=80",
    price: "₹240",
    averageRating: 4.9,
    reviewCount: 342,
    spice_level: 4,
    sweetness_level: 1,
    tag: "Crowd Favorite 🔥",
  },
  {
    id: 102,
    name: "Double Cheese Burst Pizza",
    restaurant_name: "Crust & Craft",
    category: "Italian",
    description: "Hand-tossed crust overloaded with mozzarella, cheddar, bell peppers, olives, and herb marinara.",
    image_url: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&auto=format&fit=crop&q=80",
    price: "₹299",
    averageRating: 4.8,
    reviewCount: 289,
    spice_level: 2,
    sweetness_level: 2,
    tag: "Cheesy Goodness 🧀",
  },
  {
    id: 103,
    name: "Crispy Peri Peri Fries",
    restaurant_name: "The Fries Factory",
    category: "Fast Food",
    description: "Golden crispy potato fries generously tossed in zesty peri-peri seasoning with garlic mayo dip.",
    image_url: "https://images.unsplash.com/photo-1576107232684-1279f3908594?w=800&auto=format&fit=crop&q=80",
    price: "₹120",
    averageRating: 4.7,
    reviewCount: 198,
    spice_level: 4,
    sweetness_level: 1,
    tag: "Snack King 🍟",
  },
  {
    id: 104,
    name: "Steamed Kurkure Momos",
    restaurant_name: "Dragon Delights",
    category: "Chinese",
    description: "Crispy coated steamed dumplings served with blazing spicy red garlic chutney and creamy mayo.",
    image_url: "https://images.unsplash.com/photo-1625220194771-7ebdea0b70b4?w=800&auto=format&fit=crop&q=80",
    price: "₹130",
    averageRating: 4.8,
    reviewCount: 215,
    spice_level: 5,
    sweetness_level: 1,
    tag: "Super Spicy 🌶️",
  },
  {
    id: 105,
    name: "Molten Chocolate Lava Cake",
    restaurant_name: "Sweet Sin Bakery",
    category: "Dessert",
    description: "Warm dark chocolate sponge cake with an irresistible flowing warm fudge center.",
    image_url: "https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=800&auto=format&fit=crop&q=80",
    price: "₹160",
    averageRating: 4.9,
    reviewCount: 412,
    spice_level: 1,
    sweetness_level: 5,
    tag: "Pure Joy 🍫",
  },
  {
    id: 106,
    name: "Gourmet Smash Veggie Burger",
    restaurant_name: "Burger District",
    category: "Fast Food",
    description: "Crispy spiced vegetable patty, caramelised onions, pickles, cheese slice, and signature sauce in brioche.",
    image_url: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop&q=80",
    price: "₹180",
    averageRating: 4.6,
    reviewCount: 167,
    spice_level: 2,
    sweetness_level: 2,
    tag: "Mega Crunchy 🍔",
  },
  {
    id: 107,
    name: "Spicy Schezwan Hakka Noodles",
    restaurant_name: "Wok & Roll",
    category: "Chinese",
    description: "Wok-tossed noodles with shredded vegetables, spring onions, and fiery house-made schezwan sauce.",
    image_url: "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=800&auto=format&fit=crop&q=80",
    price: "₹170",
    averageRating: 4.7,
    reviewCount: 145,
    spice_level: 4,
    sweetness_level: 1,
    tag: "Wok Tossed 🥢",
  },
  {
    id: 108,
    name: "Crispy Ghee Podi Masala Dosa",
    restaurant_name: "Dakshin Tiffin Room",
    category: "South Indian",
    description: "Golden paper-crisp fermented crepe spiced with gunpowder podi, pure ghee, potato masala, and 3 chutneys.",
    image_url: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=800&auto=format&fit=crop&q=80",
    price: "₹110",
    averageRating: 4.9,
    reviewCount: 520,
    spice_level: 3,
    sweetness_level: 1,
    tag: "Traditional Classic 🥞",
  },
  {
    id: 109,
    name: "Delhi Street Pani Puri (6 Pcs)",
    restaurant_name: "Chaat Chowk",
    category: "Fast Food",
    description: "Crisp puffed puris filled with boiled potatoes, chickpeas, and plunged in ice-cold mint and tamarind waters.",
    image_url: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&auto=format&fit=crop&q=80",
    price: "₹60",
    averageRating: 4.9,
    reviewCount: 680,
    spice_level: 5,
    sweetness_level: 2,
    tag: "Street Hero 💧",
  },
  {
    id: 110,
    name: "Iced Caramel Macchiato",
    restaurant_name: "The Bean Haven",
    category: "Beverage",
    description: "Chilled rich espresso poured over creamy milk, vanilla syrup, and finished with buttery caramel drizzle.",
    image_url: "https://images.unsplash.com/photo-1517256064527-09c73fc73e38?w=800&auto=format&fit=crop&q=80",
    price: "₹150",
    averageRating: 4.8,
    reviewCount: 230,
    spice_level: 1,
    sweetness_level: 4,
    tag: "Energy Booster ☕",
  },
  {
    id: 111,
    name: "Creamy Paneer Butter Masala",
    restaurant_name: "Punjab Junction",
    category: "Indian",
    description: "Melt-in-mouth cottage cheese cubes simmered in rich tomato, butter, and cashew gravy with kasuri methi.",
    image_url: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=800&auto=format&fit=crop&q=80",
    price: "₹260",
    averageRating: 4.8,
    reviewCount: 310,
    spice_level: 2,
    sweetness_level: 3,
    tag: "Comfort Feast 🍲",
  },
  {
    id: 112,
    name: "Brown Sugar Boba Milk Tea",
    restaurant_name: "Bubble Pop Café",
    category: "Beverage",
    description: "Chewy warm brown sugar tapioca pearls drowned in iced fresh organic milk and black tea.",
    image_url: "https://images.unsplash.com/photo-1558857563-b371033873b8?w=800&auto=format&fit=crop&q=80",
    price: "₹170",
    averageRating: 4.7,
    reviewCount: 190,
    spice_level: 1,
    sweetness_level: 5,
    tag: "Viral Sensation 🧋",
  },
];
